### ISSUE TITLE
Camera Settings -> Switch on/off the camera

### ISSUE THREAD

**Issue by tunerooster** [alienatedsec/yi-hack-v5#36] opened 2021-04-21 12:21 UTC
When I turn the camera off using HTTP  page:
```
Camera Settings -> Switch on/off the camera -> OFF
```
It does _not_ turn the camera off.  E.g., I can still stream via rtsp.
Allwinner v5 works.

P.S.  `ipc_cmd -t OFF` works.

**Comment by kwirk** [comment] 2021-04-21 17:49
Working okay on Yi Dome 1080p.

Does `http://x.x.x.x:8080/cgi-bin/camera_settings.sh?switch_on=no` work?  This would avoid attempting to set other settings just in case they are the issue.

**Comment by tunerooster** [comment] 2021-04-22 09:39
Yes, this works:

```
http://root:xxxxxxx@driveway:8080/cgi-bin/camera_settings.sh?switch_on=no
http://root:xxxxxxx@driveway:8080/cgi-bin/camera_settings.sh?switch_on=yes
```

**Comment by alienatedsec** [comment] 2022-09-27 17:03
@tunerooster I cannot reproduce it in v0.3.3
Please check and/or close this issue if already resolved

**Closed** 2022-12-05 20:32 UTC
