### ISSUE TITLE
MQTT status changes many times per second (offline/online) when RTSP server is activated (0.4.1.e)

### ISSUE THREAD

**Issue by Sigfrodr** [alienatedsec/yi-hack-v5#333] opened 2024-02-04 21:00 UTC
**Describe the bug**
MQTT "status" changes many times per second (offline/online) when RTSP server is activated (0.4.1.e)

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate MQTT
2. Activate RTSP

**Expected behaviour**
"status" must be consistent

**Set Up Details (please complete the following information):**
 - Firmware Version: 0.4.1e
 - Device: YI DOME1080P

**Comment by waleed-alharthi** [comment] 2024-02-05 12:40
I have the same camera. Enabling RTSP (Both), sound, paging file and MQTT during initial setup. All cameras go into boot loop the second day. Not sure if it's related.

**Comment by Sigfrodr** [comment] 2024-02-05 15:07
> I have the same camera. Just flashed the same version (0.4.1.e). Enabled RTSP (Both), sound, paging file and MQTT during initial setup. Disabled cloud and recording. All cameras go into boot loop the second day. Not sure if it's related. I have the same issue on any version.

I confirm the bootloop on the 2nd day too.

**Comment by waleed-alharthi** [comment] 2024-02-05 15:22
> @waleed-alharthi a one of those functions must keep breaking a service and results in boot looping. I'll have a look

I forgot to enable MQTT on one of the cameras. It's the only camera up and running for months.

**Comment by waleed-alharthi** [comment] 2024-02-06 08:47
I've flashed one and kept MQTT off yesterday. It still went into boot loop today. I'll try something else.

**Comment by Minims** [comment] 2024-02-08 22:22
Same here after upgrading an outdoor 9CUS from 0.4.1.d to 0.4.1.e

**Comment by Minims** [comment] 2024-02-10 13:30
I can confirm the issue is still present on 0.4.1f

**Comment by alienatedsec** [comment] 2024-02-10 13:39
I also noticed the same and need to work on this at some point.

**Comment by alienatedsec** [comment] 2024-02-11 00:24
@roleoroleo do you experience the same?
![chrome_RW4hwW3Yld](https://github.com/alienatedsec/yi-hack-v5/assets/73167064/2ab161b7-5f42-4f9e-99bc-75252029ab88)

**Comment by roleoroleo** [comment] 2024-02-11 12:58
There are several possibilities.
I need some more information.
Please, open a mqtt client (MQTT-Explorer for example) and check if the broker receives messages from the cam in the status topic.
Especially, check if the status changes online-offline-online...

Then, connect to the cam with a ssh session, kill mqttv4 and restart it manually.
Read the output and check if the cam has a stable connection with the broker.

**Comment by roleoroleo** [comment] 2024-02-11 16:04
The problem is 2 mqttv4 processes running.
But I don't know who starts the 2nd process.

**Comment by alienatedsec** [comment] 2024-02-11 16:19
@roleoroleo wd_rtsp seems to restart the mgttv4 a lot

**Comment by roleoroleo** [comment] 2024-02-11 17:33
Maybe, but the syntax of the check seems to be ok.

**Comment by alienatedsec** [comment] 2024-02-11 20:36
Found the issue and this is `wd_rtsp.sh` caused by this change https://github.com/alienatedsec/yi-hack-v5/commit/29f8cdb25303e455a307070192b8a16e597b07e2

When `wd_rtsp.sh` is executed, it does not see `mqttv4` and launches it. After 30 seconds, the above kicks another `mqttv4` process.

My question is - are these 30 seconds needed @fidesachates ?

**Comment by fidesachates** [comment] 2024-02-11 21:56
Well it's interesting... as I noted in my PR, I added it because the mqtt was failing to start for me due to this error:

`Can't open mqueue /ipc_dispatch_1. Error: No such file or directory`

which I had attributed to the previous command at the time of that commit, ipc_multiplexer to not have fully started. However, immediately after my commit, this commit was added which removed it so now I don't know if it's needed. Feel free to roll it back and I can always resubmit a pr if needed. 

https://github.com/alienatedsec/yi-hack-v5/commit/bd032ddb7fda8b3375fdd06b4d8ded11024cbaf2#diff-255ce4d35bec53378a47c9c7a0488aa2944e89d216f4a9ee8f428e109d47744dL227-L228

**Comment by Minims** [comment] 2024-02-12 22:52
It seems working great in 0.4.1h

status is ok
I can change the led status / switch status with success.

I needed to remove retain message on camera settings to make it work

**Comment by alienatedsec** [comment] 2024-02-14 22:25
Which retain message? @Minims

**Comment by Minims** [comment] 2024-02-14 22:49
Set this to 0 by default

https://github.com/alienatedsec/yi-hack-v5/blob/master/src/static/static/home/yi-hack-v5/etc/mqtt_advertise.conf#L42

**Comment by alienatedsec** [comment] 2024-02-19 07:34
This is fixed in the latest pre-release - please raise another issue if needed

**Closed by alienatedsec** 2024-02-19 07:34 UTC
Labels: bug
